### ISSUE TITLE
Cannot run gui on linux

### ISSUE THREAD

**Issue by b3m3bi** [poseidon-fisheries/poseidon-gui#1]
Hi!

I followed the installation instructions and I had no problem with cloning the repo, getting the submodule and building it with gradle. However I can't run the model. When I try to run the model with `./gradlew run` I get the following error :

```
> Task :app:run FAILED
Error: Could not find or load main class uk.ac.ox.poseidon.gui.Main

FAILURE: Build failed with an exception.
```

Here is an image of the full output of the  error.

![image](https://github.com/poseidon-fisheries/poseidon-gui/assets/46090720/ec2892e6-904f-4052-a5cc-f404cf7efabf)

**Comment by nicolaspayette** [comment]
Hi! Thanks for reporting this. Somehow there was a mismatch between the location of the `Main` class as declared in the build file and its actual location in the project.

I moved `Main` to the `gui` package where gradle expected it to be. If you try again by running `git pull` and then `./gradlew run`, it should work. Let me know how it goes!

**Comment by b3m3bi** [comment]
Thanks for the quick response!
After pulling the changes I tried `./gradlew run` again but I got a new error:

```
> Task :app:run FAILED
Current Working Directory: /home/lggj/Pruebas/a/poseidon-gui/app/.
log4j:WARN No appenders could be found for logger (org.metawidget.config.impl.BaseConfigReader).
log4j:WARN Please initialize the log4j system properly.
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Failed to read inputs/epo_inputs/species_codes.csv with exception: java.io.FileNotFoundException: inputs/epo_inputs/species_codes.csv (No such file or directory)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952)
        at uk.ac.ox.oxfish.biology.SpeciesCodesFromFileFactory.get(SpeciesCodesFromFileFactory.java:52)
        at uk.ac.ox.oxfish.biology.tuna.BiomassInitializerFactory.<init>(BiomassInitializerFactory.java:55)
        at uk.ac.ox.oxfish.model.scenario.EpoBiomassScenario.<init>(EpoBiomassScenario.java:85)
        at uk.ac.ox.poseidon.gui.ScenarioSelector.<init>(ScenarioSelector.java:63)
        at uk.ac.ox.poseidon.gui.Main.main(Main.java:68)
Caused by: java.lang.RuntimeException: Failed to read inputs/epo_inputs/species_codes.csv with exception: java.io.FileNotFoundException: inputs/epo_inputs/species_codes.csv (No such file or directory)
        at uk.ac.ox.oxfish.utility.csv.CsvParserUtil.getReader(CsvParserUtil.java:60)
        at uk.ac.ox.oxfish.utility.csv.CsvParserUtil.getReader(CsvParserUtil.java:53)
        at uk.ac.ox.oxfish.utility.csv.CsvParserUtil.recordStream(CsvParserUtil.java:42)
        at uk.ac.ox.oxfish.biology.SpeciesCodesFromFileFactory.getSpeciesCodes(SpeciesCodesFromFileFactory.java:33)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 9 more

FAILURE: Build failed with an exception.
```

I also tried cloning again the repo and submodule and building the app, but got the same error when runing `./gradlew run`.

**Comment by nicolaspayette** [comment]
The `poseidon-gui` repo was pointing to a version of the `POSEIDON` repo that itself pointed to a private  `epo_inputs` submodule that you cannot download. 

I changed it (https://github.com/poseidon-fisheries/poseidon-gui/commit/7373244473abe004036a0b43d6a4e588087dc968) so that you should be able to load the GUI without it if you pull and compile again.

Let me know how it goes. And sorry if the ride is a bit bumpy; this is a legacy part of the project and I don't think any other external user has tried it recently.

**Comment by nicolaspayette** [comment]
Closing this for now but feel free to get back to me if the issue wasn't fixed for you.
